import type { Metadata } from "next";
import { Geist, Geist_Mono, Goldman, Poppins} from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "@/components/mine/header/Header";
import Footer from "@/components/mine/footer/Footer";

const goldman = Goldman({
  variable: "--font-goldman",
  weight:['400', '700']
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight:['400', '500', '600']
});

const clashDisplay = localFont({
  src:'../../public/clash-display/ClashDisplay-Medium.otf',
  variable:"--font-clashDisplay",
  weight:'500'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${goldman.variable} ${poppins.variable} ${clashDisplay.variable} antialiased`}
      >
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
